name: Basic CI
on: [push, pull_request]

jobs:
  basic_ci:
    name: Basic CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - humble
          - iron
          - rolling

        # Define the Docker image(s) associated with each ROS distribution.
        # The include syntax allows additional variables to be defined, like
        # docker_image in this case. See documentation:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-configurations-in-a-matrix-build
        #
        # Platforms are defined in REP 3 and REP 2000:
        # https://ros.org/reps/rep-0003.html
        # https://ros.org/reps/rep-2000.html
        include:

          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble

          # Iron Irwini (May 2023 - November 2024)
          - docker_image: ubuntu:jammy
            ros_distribution: iron

          # Rolling Ridley (No End-Of-Life)
          - docker_image: ubuntu:jammy
            ros_distribution: rolling

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - uses: ros-tooling/setup-ros@v0.7
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: ros_ws/src
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: rosidl_adapter_proto rosidl_typesupport_protobuf rosidl_typesupport_protobuf_cpp rosidl_typesupport_protobuf_c rosidl_typeadapter_protobuf_test
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/${{ matrix.ros_distribution }}/ros2.repos
